[package]
edition = "2018"
name = "aave-js"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1"
napi-derive = "1"
bigdecimal = "0.2"
num-bigint = "0.4"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
