[package]
authors = ["Sakulstra"]
edition = "2018"
name = "aave-rs"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1.7"
napi-derive = "1"
bigdecimal = "0.2"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
